### ISSUE TITLE
New tab opens in rightmost position rather than next to current tab

### ISSUE THREAD

**Issue by dersuchmann** [sblask-webextensions/webextension-open-tabs-in-foreground#94]
### New Issue Checklist (tick off like this: `[x]`)

- [X] I checked existing issues (open and closed) for possible duplicates
- [X] I can reproduce the problem on the latest stable version (not nightly!) -> **if that's the version from the Chrome Web Store, because I can only confirm with that one**

### What is your browser?

- [ ] Firefox
- [X] Chrome

### What is your operating system?

- [ ] Linux
- [ ] Mac
- [X] Windows

### Description (please include examples/screenshots where applicable)

Chrome default behavior when using middle click is to open the new tab directly to the right of the current tab. But with this extension active, the new tab is always opened as the rightmost tab of the window, and not next to the current tab.

Might be able to look at this myself, but not now, so any help is much appreciated.

**Comment by sblask** [comment]
I've got a separate extension for that: https://github.com/sblask-webextensions/webextension-open-tabs-next-to-current
